"""Regenerate `contracts/finding-occurrence-v1.json`.

    PYTHONUTF8=1 python3 contracts/regenerate-finding-occurrence-v1.py

Kept in the repo as the vectors' provenance. The framing is transcribed here from
the contract text and NOT imported from `identity/occurrence.py`, because vectors
generated by the implementation they check agree with themselves and with nothing
else - `identity/tests/test_occurrence.py` carries a third transcription for the
same reason.

`old()` is the separator-joined recipe this contract replaces. It is retained
only so the run prints its evidence: the `separator-*` vector pair really did
share a preimage under it, while the `digit-boundary-*` pair did not and is a
guard against a future unframed-numeric "simplification" rather than a past
defect. A claim about a defect should be reproducible, not remembered.
"""
import hashlib
import json
import pathlib

US = chr(0x1F)
NUL = chr(0x00)


def oid(run, name, pat, path, line, col):
    def f(v):
        b = v.encode("utf-8")
        return ("%d:" % len(b)).encode("ascii") + b
    c = "null" if col is None else str(col)
    pre = ("finding-occurrence/v1" + NUL).encode("ascii") + b"".join(
        f(x) for x in (run, name, pat, path, str(line), c))
    return hashlib.sha256(pre).hexdigest()[:32]


def old(run, name, pat, path, line, col):
    """The separator-joined recipe this replaces, kept only to demonstrate that the
    new vectors really do pin collisions it could not tell apart."""
    c = "" if col is None else str(col)
    return hashlib.sha256(
        US.join([run, name, pat, path, str(line), c]).encode("utf-8")).hexdigest()[:32]


RUN = "audit-20260729T100000Z-3f0c1d2e4b5a6789abcdef0123456789/own-check"
RUN2 = "audit-20260730T090000Z-9e8d7c6b5a4938271605f4e3d2c1b0a9/own-check"
PAT = "9323408c303bd2cf"
PAT2 = "bf5dae4e2ebff293"
UPATH = "src/Отчёт/Форма.cs"

vectors = [
    dict(name="full-anchor", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT, path="Broker/AmountWindow.xaml.cs", start_line=72, start_column=17),
    dict(name="line-only", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT, path="Broker/AmountWindow.xaml.cs", start_line=72, start_column=None),
    dict(name="column-one", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT, path="Broker/AmountWindow.xaml.cs", start_line=72, start_column=1),
    dict(name="different-line", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT, path="Broker/AmountWindow.xaml.cs", start_line=130, start_column=17),
    dict(name="different-pattern", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT2, path="Broker/AmountWindow.xaml.cs", start_line=72, start_column=17),
    dict(name="different-producer", producer_run_id=RUN, producer_name="codeql",
         pattern_id=PAT, path="Broker/AmountWindow.xaml.cs", start_line=72, start_column=17),
    dict(name="different-run", producer_run_id=RUN2, producer_name="own-check",
         pattern_id=PAT, path="Broker/AmountWindow.xaml.cs", start_line=72, start_column=17),
    dict(name="unicode-path", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT, path=UPATH, start_line=8, start_column=4),
    dict(name="large-line", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT, path="Broker/GTD.cs", start_line=5192, start_column=None),
    # The pair a separator-joined recipe cannot tell apart: under US.join both
    # produce the same preimage. Framed, they do not. Frozen so the ambiguity
    # cannot come back as a "simplification".
    dict(name="separator-inside-producer-name", producer_run_id="a",
         producer_name="b" + US + "c", pattern_id=PAT, path="A.cs",
         start_line=1, start_column=None),
    dict(name="separator-shifted-into-run-id", producer_run_id="a" + US + "b",
         producer_name="c", pattern_id=PAT, path="A.cs",
         start_line=1, start_column=None),
    # A guard, not a past defect: these two were already distinct while the
    # numerics were separator-joined, and would collide the moment someone
    # emitted them unframed.
    dict(name="digit-boundary-line-12-col-3", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT, path="A.cs", start_line=12, start_column=3),
    dict(name="digit-boundary-line-1-col-23", producer_run_id=RUN, producer_name="own-check",
         pattern_id=PAT, path="A.cs", start_line=1, start_column=23),
]
for v in vectors:
    v["occurrence_id"] = oid(v["producer_run_id"], v["producer_name"], v["pattern_id"],
                             v["path"], v["start_line"], v["start_column"])

NO_COL = "physical-anchor-missing:start-column"
NO_RUN = "occurrence-id-unavailable:producer-run-id"
AMBIG = "occurrence-id-unavailable:ambiguous-physical-anchor"
NO_LINE = "occurrence-id-unavailable:start-line"
NO_PATH = "occurrence-id-unavailable:path"


def A(p, l, c):
    return {"path": p, "start_line": l, "start_column": c}


gate = [
    dict(name="everything-known", pattern_id=PAT, physical_anchor=A("Broker/A.cs", 72, 17),
         producer_run_id=RUN, producer_name="own-check", ambiguous=False,
         occurrence_id=oid(RUN, "own-check", PAT, "Broker/A.cs", 72, 17),
         identity_limitations=[]),
    dict(name="line-only-unique-is-a-degradation-not-a-blocker", pattern_id=PAT,
         physical_anchor=A("Broker/A.cs", 72, None), producer_run_id=RUN,
         producer_name="own-check", ambiguous=False,
         occurrence_id=oid(RUN, "own-check", PAT, "Broker/A.cs", 72, None),
         identity_limitations=[NO_COL]),
    dict(name="line-only-ambiguous-is-a-blocker", pattern_id=PAT,
         physical_anchor=A("Broker/A.cs", 72, None), producer_run_id=RUN,
         producer_name="own-check", ambiguous=True,
         occurrence_id=None, identity_limitations=sorted([AMBIG, NO_COL])),
    dict(name="ambiguous-even-with-a-column", pattern_id=PAT,
         physical_anchor=A("Broker/A.cs", 72, 17), producer_run_id=RUN,
         producer_name="own-check", ambiguous=True,
         occurrence_id=None, identity_limitations=[AMBIG]),
    dict(name="no-run-id", pattern_id=PAT, physical_anchor=A("Broker/A.cs", 72, 17),
         producer_run_id=None, producer_name="own-check", ambiguous=False,
         occurrence_id=None, identity_limitations=[NO_RUN]),
    dict(name="no-run-id-and-no-column", pattern_id=PAT,
         physical_anchor=A("Broker/A.cs", 72, None), producer_run_id=None,
         producer_name="own-check", ambiguous=False,
         occurrence_id=None, identity_limitations=sorted([NO_RUN, NO_COL])),
    dict(name="empty-run-id-is-not-a-run-id", pattern_id=PAT,
         physical_anchor=A("Broker/A.cs", 72, 17), producer_run_id="",
         producer_name="own-check", ambiguous=False,
         occurrence_id=None, identity_limitations=[NO_RUN]),
    dict(name="no-start-line", pattern_id=PAT, physical_anchor=A("Broker/A.cs", None, None),
         producer_run_id=RUN, producer_name="own-check", ambiguous=False,
         occurrence_id=None, identity_limitations=sorted([NO_LINE, NO_COL])),
    dict(name="no-path", pattern_id=PAT, physical_anchor=A("", 72, 17),
         producer_run_id=RUN, producer_name="own-check", ambiguous=False,
         occurrence_id=None, identity_limitations=[NO_PATH]),
]

doc = {
    "contract": "finding-occurrence/v1",
    "id_length": 32,
    "domain_prefix": "finding-occurrence/v1" + NUL,
    "null_column": "null",
    "encoding": [
        "Each field is length-prefixed: <byte length in decimal> ':' <utf-8 bytes>.",
        "The six fields, in order: producer_run_id, producer_name, pattern_id, path,",
        "start_line (canonical decimal), start_column ('null' when absent).",
        "The concatenation is prefixed with domain_prefix and hashed with SHA-256; the",
        "first id_length hex characters are the id.",
        "NOT separator-joined. Under a raw <US> join, ('a', 'b<US>c') and ('a<US>b', 'c')",
        "produce the SAME preimage -- two different occurrences under one id. That pair",
        "is pinned below and really did collide under the recipe this replaces.",
        "The digit-boundary pair is a guard rather than a past defect: (12, 3) and",
        "(1, 23) were distinct while the numerics were separator-joined too, and would",
        "collide the moment someone emitted them unframed. Framing removes the question",
        "for every field at once, instead of forbidding a byte in a path.",
    ],
    "notes": [
        "The gate matters more than the hash. An occurrence id is computed only when the",
        "run, the producer, the pattern and an UNAMBIGUOUS physical anchor are all known.",
        "producer_version, config_digest and source_commit may be null without blocking.",
        "A missing start_column is a degradation (physical-anchor-missing:start-column),",
        "not automatically a blocker -- a line-only anchor still identifies an occurrence",
        "while it stays unique within the producer run. It becomes a blocker exactly when",
        "two records share it. There is no ordinal tiebreaker: an ordinal would make",
        "identity depend on emission order, the same defect that disqualifies the SARIF",
        "ownAudit/v1 fingerprint as an identity.",
        "A digest of the SARIF bytes is NOT a run id -- that value is input_digest, a",
        "provenance field. Two runs can serialize identically; two serializers of one run",
        "can differ.",
    ],
    "vectors": vectors,
    "gate": gate,
    "distinct_occurrences": [
        ["full-anchor", "different-line"],
        ["full-anchor", "different-pattern"],
        ["full-anchor", "different-producer"],
        ["full-anchor", "different-run"],
        ["full-anchor", "line-only"],
        ["line-only", "column-one"],
        ["separator-inside-producer-name", "separator-shifted-into-run-id"],
        ["digit-boundary-line-12-col-3", "digit-boundary-line-1-col-23"],
    ],
}

p = pathlib.Path("contracts/finding-occurrence-v1.json")
p.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

ids = {v["name"]: v["occurrence_id"] for v in vectors}
for a, b in doc["distinct_occurrences"]:
    if ids[a] == ids[b]:
        raise SystemExit("collision between %s and %s" % (a, b))

o1 = old("a", "b" + US + "c", PAT, "A.cs", 1, None)
o2 = old("a" + US + "b", "c", PAT, "A.cs", 1, None)
o3 = old(RUN, "own-check", PAT, "A.cs", 12, 3)
o4 = old(RUN, "own-check", PAT, "A.cs", 1, 23)
print("separator pair collided under the OLD recipe:", o1 == o2)
print("digit pair collided under the OLD recipe:    ", o3 == o4)
print("distinct under the NEW framing:              ",
      ids["separator-inside-producer-name"] != ids["separator-shifted-into-run-id"],
      ids["digit-boundary-line-12-col-3"] != ids["digit-boundary-line-1-col-23"])
print("written %s with %d vectors" % (p, len(vectors)))
