"""Normalization contract + port-parity tests. Bare python3 or pytest:

    PYTHONUTF8=1 PYTHONPATH=. python3 aggregate/tests/test_normalize.py

The load-bearing check is PARITY: `fixtures/parity/expected-findings.json` was
generated by the reference implementation this module was ported from
(`Own.NET/audit/aggregate/normalize.py` reading the YAML taxonomy - see
`fixtures/parity/PROVENANCE.md`), and the port must reproduce it **byte for
byte**. A port whose output is merely "close" is a rewrite wearing a port's name.

Since slice 1B the payload also carries identity and provenance, so the diff runs
through `project_v1` - the v2 payload seen through v1 eyes. The golden is NOT
regenerated for the new schema: 1B promised to add to those ten fields, never to
touch them, and a golden refreshed from the code under test would make that
promise unfalsifiable. The 1B behaviour has its own fixtures under
`fixtures/identity/`, where the gate is exercised on its own terms.

The golden alone is not enough, though: regenerate it from a changed
implementation and it agrees with itself and with nothing else. So the semantics
the golden encodes are also spelled out here as checks - the OWN001 resource
split, longest-prefix path stripping, the suppression rule, the coverage ledger.
Those are the outside opinion on the bytes.

Two further checks run only when a reference checkout is present
(`OWNNET_REF=/path/to/Own.NET`): the golden is re-derived from the reference
implementation, and the JSON taxonomy is re-verified as a faithful transcription
of the YAML it came from. They are skipped loudly, never silently - a skipped
check that prints nothing reads exactly like a passing one.

-O-safe (explicit raises, no bare assert). ASCII-only output.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, ROOT)

from aggregate import provenance as prov                                         # noqa: E402
from aggregate.normalize import (                                                # noqa: E402
    DEFAULT_TAXONOMY, SCHEMA_VERSION, V1_FIELDS, TaxonomyError, build_payload,
    categorize, coverage, finding_to_dict, load_taxonomy, normalize_results, project_v1,
)
from aggregate.sarif_read import norm_path, parse_sarif                          # noqa: E402
from identity.occurrence import (                                                # noqa: E402
    LIMIT_AMBIGUOUS_ANCHOR, LIMIT_NO_RUN_ID, LIMIT_NO_START_COLUMN, LIMIT_NO_START_LINE,
)

FIX = os.path.join(HERE, "fixtures", "parity")
GOLDEN = os.path.join(FIX, "expected-findings.json")
IDFIX = os.path.join(HERE, "fixtures", "identity")

#: The invocation the golden was generated with. The three overlapping spellings of
#: one worktree are what `Run-Audit.ps1` really passes; they are what makes
#: longest-prefix stripping observable rather than theoretical.
TOOLS = ("own-check", "codeql", "infersharp", "roslyn")
STRIPS = ["/work", "/work/target", "target"]

fails: list[str] = []
skips: list[str] = []


def check(cond: bool, msg: str) -> None:
    if not cond:
        fails.append(msg)


def _inputs() -> list[tuple[str, str]]:
    return [(t, os.path.join(FIX, f"{t}.sarif")) for t in TOOLS]


def main() -> int:
    tax = load_taxonomy()
    payload = build_payload(_inputs(), tax, list(STRIPS))
    got = json.dumps(project_v1(payload), indent=2)

    # ---- 1. PARITY, through the v1 projection.
    #         The golden was generated by the REFERENCE implementation and is not
    #         regenerated when the schema grows - slice 1B (Own.NET#266) added
    #         identity and provenance ON TOP of the ten frozen fields, so the port's
    #         output projected back down to v1 must still be those exact bytes.
    #         If this fails, 1B changed something it promised only to add to; the
    #         answer is to find what moved, not to refresh the golden.
    with open(GOLDEN, encoding="utf-8") as fh:
        want = fh.read()
    check(got == want,
          "the v1 projection drifted from the reference payload - diff with:\n"
          "  PYTHONUTF8=1 PYTHONPATH=. python3 aggregate/normalize.py "
          + " ".join(f"--sarif {t}={FIX}/{t}.sarif" for t in TOOLS)
          + " " + " ".join(f"--strip {s}" for s in STRIPS)
          + f" --json /tmp/got.json   # then project and diff against {GOLDEN}")
    check(payload["schema_version"] == SCHEMA_VERSION,
          f"payload schema_version is {payload.get('schema_version')!r}")

    by_path = {f["path"]: f for f in payload["findings"]}
    cov = payload["coverage"]

    # ---- 2. The OWN001 umbrella split, which is the whole reason normalization
    #         is not a flat rule->category lookup.
    for path, (cat, name) in {
        "Broker/AmountWindow.xaml.cs": (2, "subscription-leak"),
        "Broker/Poller.cs": (3, "timer-leak"),
        "Broker/Report.cs": (1, "idisposable-leak"),
        "Broker/Pool.cs": (1, "idisposable-leak"),
        "Broker/Io.cs": (1, "idisposable-leak"),          # no tag -> the "*" arm
        "Broker/Escape.cs": (2, "region-escape"),         # OWN014, NOT subscription-leak
        "Broker/View.xaml.cs": (2, "xaml-subscription-leak"),
    }.items():
        f = by_path.get(path)
        check(f is not None and (f["category"], f["category_name"]) == (cat, name),
              f"{path}: expected ({cat},{name}), got "
              f"{None if f is None else (f['category'], f['category_name'])}")
    # the tag is matched case- and space-insensitively
    check(by_path.get("Broker/CaseTag.cs", {}).get("category") == 2,
          "[Resource:  Subscription Token ] must resolve like [resource: subscription token]")

    # ---- 3. Path normalization. Every spelling below is one of the shapes the four
    #         tools really emit; getting any of them wrong misfiles a whole tool's
    #         findings into a module that does not exist.
    for path in ("Broker/Sub/Windows.cs",      # backslashes -> forward slashes
                 "Broker/Scheme.cs",           # file:/// scheme removed, then stripped
                 "Broker/Dotted.cs",           # leading ./ removed
                 "Broker/Longest.cs"):         # LONGEST strip prefix won
        check(path in by_path, f"path normalization lost {path}")
    check(norm_path("/work/target/x.cs", ["/work", "/work/target"]) == "x.cs",
          "the longest strip prefix must win, not the first one listed")

    # ---- 4. Degenerate result shapes still produce a finding rather than a crash or
    #         a silent drop - except the one documented gap.
    check(by_path.get("Broker/NoLine.cs", {}).get("line") == 0,
          "a result with no startLine must read as line 0, not be dropped")
    check(by_path.get("Broker/BadLine.cs", {}).get("line") == 0,
          "a non-integer startLine must read as line 0")
    check(by_path.get("Broker/RuleObj.cs", {}).get("rule") == "OWN001",
          "ruleId must fall back to rule.id")
    check(by_path.get("Broker/NoMessage.cs", {}).get("message") == "",
          "a result with no message text must read as an empty message")
    check(by_path.get("Broker/EmptyRule.cs", {}).get("category") == 0,
          "an empty ruleId must land in uncategorized, not match a glob")
    # KNOWN GAP, pinned so it cannot change unnoticed: a result with no location is
    # dropped and counted nowhere. own-check.sarif carries 20 results; the ledger
    # sees 19. Fixing that is a separate change with a separate payload.
    own_results = json.load(open(os.path.join(FIX, "own-check.sarif"), encoding="utf-8"))
    n_own = sum(len(run.get("results", [])) for run in own_results["runs"])
    n_read = len(parse_sarif(open(os.path.join(FIX, "own-check.sarif"), encoding="utf-8").read(),
                             "own-check", []))
    check((n_own, n_read) == (20, 19),
          f"locationless-result handling changed: {n_read} read of {n_own} results")

    # ---- 5. Suppression is by path OR message, counted and never hidden.
    check(cov["suppressed"] == 2 and cov["suppressed_by"] == {"third-party: DevExpress.": 2},
          f"third-party suppression drifted: {cov['suppressed_by']}")
    check("DevExpress.Xpf/Grid/Helper.cs" not in by_path,
          "a suppressed finding must not appear in the scored findings")
    check("Broker/Cast.cs" not in by_path,
          "suppression must read the message too, not only the path")
    check(cov["total"] - cov["kept"] == cov["suppressed"] + cov["analysis_skipped"],
          "the ledger must account for every finding it drops")

    # ---- 6. Coverage notes are routed out of scoring, not counted as verdicts.
    check(cov["analysis_skipped_by"] == {"OWN050": 1},
          f"OWN050 must be an analysis-skipped note: {cov['analysis_skipped_by']}")
    check("OWN050" not in cov["uncategorized_rules"],
          "a coverage note must not pollute the uncategorized ledger")
    check("Broker/Unknown.cs" not in by_path, "an OWN050 note must not be scored")

    # ---- 7. Unmapped rules surface by name instead of vanishing.
    for rule in ("FOO999", "XAML999", "THREAD_SAFETY_VIOLATION", "NULLPTR_DEREFERENCE",
                 "CS0219", ""):
        check(rule in cov["uncategorized_rules"],
              f"unmapped rule {rule!r} must be surfaced in coverage")

    # ---- 8. Glob precedence: exact beats glob, longer glob beats shorter.
    check(categorize("CA2000", None, tax.rules)[0] == 1, "exact CA2000 must beat the CA2* glob")
    check(categorize("CA2201", None, tax.rules)[0] == 14, "CA2* glob -> general-quality")
    check(categorize("CA1822", None, tax.rules)[0] == 14, "CA1* glob -> general-quality")
    check(categorize("PULSE_RESOURCE_LEAK", None, tax.rules)[0] == 1,
          "*RESOURCE_LEAK glob -> idisposable-leak")
    check(tax.severity_for(1) == "P1" and tax.severity_for(0) == "P3",
          "category severity baseline drifted")

    # ---- 9. The record is the ten frozen fields PLUS exactly the four slice-1B
    #         added. Pinned as an exhaustive set in both directions: a field that
    #         quietly appears is a field consumers start depending on before anyone
    #         decided it should exist, and a field that quietly vanishes breaks them.
    emitted = sorted({k for f in payload["findings"] for k in f})
    check(emitted == sorted(list(V1_FIELDS) + ["identity_limitations", "occurrence_id",
                                               "pattern_id", "physical_anchor"]),
          f"the normalized record grew or lost a field: {emitted}")
    check(list(payload["findings"][0])[:len(V1_FIELDS)] == list(V1_FIELDS),
          "the ten v1 fields must keep their frozen order and come first")

    # ---- 10. No cross-checkout import in production. The reference reached into a
    #          neighbouring Own.NET worktree with a sys.path.insert; that is exactly
    #          what this port exists to end, so it is asserted rather than trusted.
    #          Parsed, not grepped: the docstrings discuss `oracle_compare` and
    #          `Own.NET` on purpose, and only real import statements are the defect.
    import ast
    for mod in ("normalize.py", "sarif_read.py", "__init__.py"):
        with open(os.path.join(ROOT, "aggregate", mod), encoding="utf-8") as fh:
            tree = ast.parse(fh.read(), filename=mod)
        names: list[str] = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names += [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                names.append(node.module or "")
        for name in names:
            check("oracle_compare" not in name,
                  f"aggregate/{mod}: production imports {name!r} - the port exists to stop "
                  "reading Python out of a neighbouring Own.NET checkout")

    # ---- 11. Taxonomy loader: `_`-prefixed keys are documentation, a non-object
    #          rule spec is an error rather than a category silently reading as 0.
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        p = os.path.join(td, "t.json")
        with open(p, "w", encoding="utf-8") as fh:
            json.dump({"_doc": ["prose"], "rules": {"_note": "prose", "R1": {"category": 7,
                       "name": "x"}}, "category_severity": {"7": "P1"}}, fh)
        t = load_taxonomy(p)
        check(list(t.rules) == ["R1"], f"documentation keys leaked into the rules: {list(t.rules)}")
        check(categorize("R1", None, t.rules) == (7, "x"), "a plain rule spec must still resolve")
        with open(p, "w", encoding="utf-8") as fh:
            json.dump({"rules": {"R1": "not-an-object"}}, fh)
        try:
            load_taxonomy(p)
            fails.append("a malformed rule spec must raise TaxonomyError, not mis-categorize")
        except TaxonomyError:
            pass

    # ---- 12. IDENTITY (Own.NET#266 slice 1B), on its own fixture set.
    _identity_checks(tax)

    # ---- 13. Reference cross-checks (opt-in: OWNNET_REF=/path/to/Own.NET).
    ref = os.environ.get("OWNNET_REF")
    if not ref:
        skips.append("OWNNET_REF unset: golden re-derivation and YAML transcription re-check "
                     "did not run (they need an Own.NET checkout)")
    else:
        _reference_checks(ref)

    for f in fails:
        print(f"FAIL: {f}")
    for s in skips:
        print(f"SKIP: {s}")
    verdict = ("OK - v1 projection byte-identical to the reference golden"
               if not fails else f"FAIL - {len(fails)} check(s) failed")
    print(f"aggregate/normalize: {verdict} ({len(payload['findings'])} scored of "
          f"{cov['total']} read, {len(TOOLS)} tools, schema {payload['schema_version']}), "
          f"{len(skips)} check(s) skipped")
    return 1 if fails else 0


def _id_inputs() -> list[tuple[str, str]]:
    return [(t, os.path.join(IDFIX, f"{t}.sarif")) for t in ("own-check", "codeql")]


def _identity_checks(tax) -> None:
    """The slice-1B gate, end to end through the normalizer.

    The fixtures mirror what the recorded corpus actually looks like: own-check
    emits no column at all (0 of 613 results in the STS run), CodeQL emits one
    for every result. Both a line-only collision and a fully-identical
    column-bearing collision are planted, because ambiguity is not cured by
    having a column - only by the column discriminating.
    """
    ins = _id_inputs()

    # 12a. NO MANIFEST -> no run identity -> no occurrence ids anywhere, and every
    #      record says why. This is the state of the whole recorded STS corpus,
    #      whose SARIF predates the provenance contract. A legacy boundary, not a
    #      schema defect - but it must be legible as one.
    bare = build_payload(ins, tax, [])
    check(all(r["occurrence_id"] is None for r in bare["findings"]),
          "without a provenance manifest no occurrence_id may be minted")
    check(all(LIMIT_NO_RUN_ID in r["identity_limitations"] for r in bare["findings"]),
          "a null occurrence_id must carry the reason, not just be null")
    check(all(r["pattern_id"] for r in bare["findings"]),
          "pattern_id does not depend on provenance and must always be present")
    for p in bare["provenance"].values():
        check(set(prov.FIELDS) | {"producer_version_source", "digest_verified", "note"}
              <= set(p),
              f"provenance must carry every field explicitly, got {sorted(p)}")
        check("note" in p,
              "`note` must be present-and-null like every other optional field, so a "
              "consumer reads None rather than testing for key presence")
        check(p["producer_run_id"] is None and p["digest_verified"] is False,
              "an unverified producer must say so rather than look complete")

    # 12b. WITH A MANIFEST -> ids appear exactly where the anchor justifies one.
    doc = build_payload(ins, tax, [], os.path.join(IDFIX, "manifest.json"))
    by = {}
    for r in doc["findings"]:
        by.setdefault((r["tool"], r["path"], r["physical_anchor"]["start_line"],
                       r["physical_anchor"]["start_column"]), []).append(r)

    # a UNIQUE line-only anchor still earns an id - the column is a degradation
    for line in (12, 40):
        recs = by[("own-check", "Broker/Vm.cs", line, None)]
        check(len(recs) == 1 and recs[0]["occurrence_id"] is not None,
              f"own-check Vm.cs:{line} - a unique line-only anchor must earn an id")
        check(recs[0]["identity_limitations"] == [LIMIT_NO_START_COLUMN],
              f"own-check Vm.cs:{line} - the weaker anchor must be recorded")
    check(by[("own-check", "Broker/Vm.cs", 12, None)][0]["occurrence_id"]
          != by[("own-check", "Broker/Vm.cs", 40, None)][0]["occurrence_id"],
          "two occurrences of one pattern at different lines must differ")
    check(by[("own-check", "Broker/Vm.cs", 12, None)][0]["pattern_id"]
          == by[("own-check", "Broker/Vm.cs", 40, None)][0]["pattern_id"],
          "...while still sharing a pattern_id - that collision is the point")

    # a COLLIDING line-only anchor earns nothing, and gets no ordinal
    dup = by[("own-check", "Broker/Dup.cs", 7, None)]
    check(len(dup) == 2 and all(r["occurrence_id"] is None for r in dup),
          "two records sharing a line-only anchor must BOTH get a null occurrence_id")
    for r in dup:
        check(r["identity_limitations"] == sorted([LIMIT_AMBIGUOUS_ANCHOR,
                                                   LIMIT_NO_START_COLUMN]),
              f"the colliding pair must name both problems: {r['identity_limitations']}")

    # a column DISCRIMINATES...
    io9 = [r for r in doc["findings"] if r["path"] == "Broker/Io.cs"]
    check(len(io9) == 2 and len({r["occurrence_id"] for r in io9}) == 2
          and all(r["occurrence_id"] for r in io9),
          "same line, different columns must yield two distinct occurrence ids")
    check(all(r["identity_limitations"] == [] for r in io9),
          "a complete anchor in an identified run has nothing to declare")
    # ...but having one is not the same as being distinguished by one
    same = [r for r in doc["findings"] if r["path"] == "Broker/Same.cs"]
    check(len(same) == 2 and all(r["occurrence_id"] is None for r in same),
          "identical anchors must yield no id even when a column is present")
    check(all(r["identity_limitations"] == [LIMIT_AMBIGUOUS_ANCHOR] for r in same),
          "a column-bearing collision must NOT claim a missing column")

    # no line at all -> nothing to anchor to
    noline = [r for r in doc["findings"] if r["path"] == "Broker/NoLine.cs"]
    check(len(noline) == 1 and noline[0]["occurrence_id"] is None
          and LIMIT_NO_START_LINE in noline[0]["identity_limitations"],
          "a result with no startLine cannot be anchored")

    # 12c. THE ANTI-ORDINAL PROPERTY. Reordering the results in a SARIF file must
    #      not change a single occurrence id. This is the whole reason the recipe
    #      refuses an ordinal tiebreaker: the SARIF `ownAudit/v1` fingerprint
    #      appends one, which makes identity depend on emission order.
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        src = json.load(open(os.path.join(IDFIX, "own-check.sarif"), encoding="utf-8"))
        for run in src["runs"]:
            run["results"].reverse()
        shuffled = os.path.join(td, "own-check.sarif")
        with open(shuffled, "w", encoding="utf-8") as fh:
            json.dump(src, fh, indent=2)
        # a manifest without an input_digest: nothing to verify against the new
        # bytes, and the point here is the ordering, not the binding.
        man = os.path.join(td, "manifest.json")
        with open(man, "w", encoding="utf-8") as fh:
            json.dump({"schema_version": prov.CONTRACT, "inputs": {"own-check": {
                "producer_run_id": "audit-20260729T100000Z/own-check",
                "producer_name": "own-check", "producer_version": None,
                "input_digest": None, "config_digest": None, "source_commit": None}}}, fh)
        a = build_payload([("own-check", os.path.join(IDFIX, "own-check.sarif"))], tax, [], man)
        b = build_payload([("own-check", shuffled)], tax, [], man)
        ids_a = sorted(r["occurrence_id"] or "" for r in a["findings"])
        ids_b = sorted(r["occurrence_id"] or "" for r in b["findings"])
        check(ids_a == ids_b,
              "reordering a SARIF file changed the occurrence ids - an ordinal or some "
              "other order-dependence crept into identity")
        check(a["provenance"]["own-check"]["digest_verified"] is False,
              "a manifest entry with no input_digest must not report itself verified")

    # 12d. Re-normalizing the same recorded run reproduces the same ids. An id that
    #      changed per normalization would describe the normalization, not the run.
    again = build_payload(ins, tax, [], os.path.join(IDFIX, "manifest.json"))
    check([r["occurrence_id"] for r in again["findings"]]
          == [r["occurrence_id"] for r in doc["findings"]],
          "occurrence ids must be deterministic for the same inputs and manifest")

    # 12e. A digest that describes other bytes is REJECTED, not degraded.
    try:
        build_payload(ins, tax, [], os.path.join(IDFIX, "manifest-stale-digest.json"))
        fails.append("a manifest whose input_digest does not match the file must raise")
    except prov.ProvenanceError:
        pass
    except Exception as e:                                       # noqa: BLE001
        # Recorded as a named failure rather than escaping: an unexpected exception
        # here would abort the whole sweep, and every later check would go unrun
        # while looking like it had never existed.
        fails.append(f"stale digest raised {type(e).__name__}, expected ProvenanceError")

    # 12f. An entry with no run id is present but useless - and only for its own
    #      producer; the other producer must keep its identity.
    partial = build_payload(ins, tax, [], os.path.join(IDFIX, "manifest-no-run-id.json"))
    cq = [r for r in partial["findings"] if r["tool"] == "codeql"]
    oc = [r for r in partial["findings"] if r["tool"] == "own-check"]
    check(all(r["occurrence_id"] is None and LIMIT_NO_RUN_ID in r["identity_limitations"]
              for r in cq),
          "a producer whose manifest entry carries no run id must get no occurrence ids")
    check(any(r["occurrence_id"] for r in oc),
          "one producer's missing run id must not cost another producer its identity")
    check(partial["provenance"]["codeql"]["note"],
          "a producer with no usable run id must carry a note saying so")

    # 12g. The ledger balances and surfaces the unclaimed manifest entry (a typo in
    #      a tool name would otherwise silently cost that producer its whole run).
    ident = doc["coverage"]["identity"]
    check("schema_version" not in ident,
          "the identity ledger must not restate the payload's schema_version - one "
          "contract declaration, one place to drift")
    check(ident["with_occurrence_id"] + ident["without_occurrence_id"] == len(doc["findings"]),
          "the identity ledger must account for every emitted record")
    check(sum(ident["by_producer"][t]["with_occurrence_id"]
              for t in ident["by_producer"]) == ident["with_occurrence_id"],
          "the per-producer identity tally must sum to the total")
    check(doc["coverage"].get("provenance_unused_entries") == ["infersharp"],
          "a manifest entry no --sarif input claimed must be surfaced in the ledger")

    # 12h. The emitted `pattern_id` and the overlay-facing alias must be the SAME
    #      bytes. Two identities disagreeing inside one file would silently orphan
    #      every stored fp-verdicts overlay against a report that looks correct.
    from viz.apply_verdicts import finding_id                                    # noqa: E402
    check(all(finding_id(r) == r["pattern_id"] for r in doc["findings"]),
          "the emitted pattern_id drifted from viz/apply_verdicts.finding_id")

    # 12i. A version the producer states in its own SARIF must not be reported as
    #      unknown just because the manifest stayed quiet about it - and where it
    #      came from must be recorded, since "the runner asserted it" and "the tool
    #      said so" are different claims. The fixture manifest leaves CodeQL's
    #      producer_version null; the SARIF driver declares semanticVersion 2.25.6.
    cqp = doc["provenance"]["codeql"]
    check(cqp["producer_version"] == "2.25.6"
          and cqp["producer_version_source"] == "sarif-driver",
          f"the observed driver version was not picked up: {cqp}")
    ocp = doc["provenance"]["own-check"]
    check(ocp["producer_version"] is None and ocp["producer_version_source"] is None,
          "a producer that declares no version must stay null, with no source")

    # 12j. ONE INPUT PER PRODUCER, enforced. Provenance is keyed by producer name
    #      and a record joins through its `tool`, so two runs under one name cannot
    #      be represented - both would answer to the same key. Until input-instance
    #      identity exists, this is a real contract and it must fail loudly rather
    #      than resolve to whichever entry survived.
    try:
        build_payload(ins + [("codeql", os.path.join(IDFIX, "codeql.sarif"))], tax, [])
        fails.append("two --sarif inputs under one producer name must raise")
    except prov.ProvenanceError:
        pass
    except Exception as e:                                       # noqa: BLE001
        fails.append(f"duplicate producer raised {type(e).__name__}, expected ProvenanceError")

    # 12k. A malformed manifest raises ProvenanceError - never AttributeError or
    #      TypeError from somewhere far from the cause, and never a run identity
    #      str()-ed out of a number that no producer ever emitted.
    for name in ("manifest-bad-types.json", "manifest-entry-not-object.json",
                 "manifest-root-not-object.json"):
        try:
            build_payload(ins, tax, [], os.path.join(IDFIX, name))
            fails.append(f"{name}: a malformed manifest must raise ProvenanceError")
        except prov.ProvenanceError:
            pass
        except Exception as e:                                   # noqa: BLE001
            fails.append(f"{name}: raised {type(e).__name__}, expected ProvenanceError")
    # A malformed manifest must exit 2 through the CLI, whatever shape the malformation
    # takes. An AttributeError escaping to a traceback and exit 1 would make the
    # failure mode depend on HOW the file was wrong.
    import subprocess
    for name in ("manifest-bad-types.json", "manifest-entry-not-object.json",
                 "manifest-root-not-object.json", "manifest-stale-digest.json"):
        proc = subprocess.run(
            [sys.executable, os.path.join(ROOT, "aggregate", "normalize.py"),
             "--sarif", f"own-check={os.path.join(IDFIX, 'own-check.sarif')}",
             "--provenance", os.path.join(IDFIX, name)],
            capture_output=True, text=True, env={**os.environ, "PYTHONUTF8": "1"})
        check(proc.returncode == 2,
              f"{name}: CLI exited {proc.returncode}, expected 2")
        check("Traceback" not in proc.stderr,
              f"{name}: CLI printed a traceback instead of a diagnosis")


def _reference_checks(ref: str) -> None:
    """Re-derive the golden from the reference implementation, and re-verify that the
    JSON taxonomy still says what the YAML it was transcribed from says."""
    ref_norm = os.path.join(ref, "audit", "aggregate", "normalize.py")
    ref_yaml = os.path.join(ref, "audit", "static", "taxonomy", "categories.yml")
    if not os.path.exists(ref_norm):
        skips.append(f"OWNNET_REF={ref}: no audit/aggregate/normalize.py there, reference "
                     "checks did not run")
        return

    import subprocess
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        out = os.path.join(td, "ref.json")
        cmd = [sys.executable, ref_norm, "--taxonomy", ref_yaml, "--json", out]
        for tool, path in _inputs():
            cmd += ["--sarif", f"{tool}={path}"]
        for s in STRIPS:
            cmd += ["--strip", s]
        env = {**os.environ, "PYTHONUTF8": "1"}
        proc = subprocess.run(cmd, capture_output=True, text=True, env=env)
        if proc.returncode != 0:
            fails.append(f"reference normalize.py failed (rc={proc.returncode}): "
                         f"{proc.stderr.strip()[:400]}")
            return
        with open(out, encoding="utf-8") as fh:
            regenerated = fh.read()
    with open(GOLDEN, encoding="utf-8") as fh:
        check(regenerated == fh.read(),
              "the committed golden is no longer what the reference implementation "
              "produces - regenerate it and re-read the diff before trusting either side")

    try:
        import yaml
    except ImportError:
        skips.append("PyYAML not importable: taxonomy transcription re-check did not run "
                     "(the audit does not depend on it; this check is developer-only)")
        return
    with open(ref_yaml, encoding="utf-8") as fh:
        y = yaml.safe_load(fh) or {}
    with open(DEFAULT_TAXONOMY, encoding="utf-8") as fh:
        j = json.load(fh)
    for key in ("rules", "category_severity", "suppress", "coverage_notes"):
        a = y.get(key)
        b = j.get(key)
        if key == "category_severity":                 # JSON object keys are strings
            a = {str(k): v for k, v in (a or {}).items()}
        check(a == b, f"taxonomy transcription drifted from the YAML in {key!r}")


if __name__ == "__main__":
    raise SystemExit(main())
