"""Normalization contract + port-parity tests. Bare python3 or pytest:

    PYTHONUTF8=1 PYTHONPATH=. python3 aggregate/tests/test_normalize.py

The load-bearing check is PARITY: `fixtures/parity/expected-findings.json` was
generated by the reference implementation this module was ported from
(`Own.NET/audit/aggregate/normalize.py` reading the YAML taxonomy - see
`fixtures/parity/PROVENANCE.md`), and the port must reproduce it **byte for
byte**. A port whose output is merely "close" is a rewrite wearing a port's name.

The golden alone is not enough, though: regenerate it from a changed
implementation and it agrees with itself and with nothing else. So the semantics
the golden encodes are also spelled out here as checks - the OWN001 resource
split, longest-prefix path stripping, the suppression rule, the coverage ledger.
Those are the outside opinion on the bytes.

Two further checks run only when a reference checkout is present
(`OWNNET_REF=/path/to/Own.NET`): the golden is re-derived from the reference
implementation, and the JSON taxonomy is re-verified as a faithful transcription
of the YAML it came from. They are skipped loudly, never silently - a skipped
check that prints nothing reads exactly like a passing one.

-O-safe (explicit raises, no bare assert). ASCII-only output.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, ROOT)

from aggregate.normalize import (                                                # noqa: E402
    DEFAULT_TAXONOMY, TaxonomyError, build_payload, categorize, coverage,
    finding_to_dict, load_taxonomy, normalize_results,
)
from aggregate.sarif_read import norm_path, parse_sarif                          # noqa: E402

FIX = os.path.join(HERE, "fixtures", "parity")
GOLDEN = os.path.join(FIX, "expected-findings.json")

#: The invocation the golden was generated with. The three overlapping spellings of
#: one worktree are what `Run-Audit.ps1` really passes; they are what makes
#: longest-prefix stripping observable rather than theoretical.
TOOLS = ("own-check", "codeql", "infersharp", "roslyn")
STRIPS = ["/work", "/work/target", "target"]

fails: list[str] = []
skips: list[str] = []


def check(cond: bool, msg: str) -> None:
    if not cond:
        fails.append(msg)


def _inputs() -> list[tuple[str, str]]:
    return [(t, os.path.join(FIX, f"{t}.sarif")) for t in TOOLS]


def main() -> int:
    tax = load_taxonomy()
    payload = build_payload(_inputs(), tax, list(STRIPS))
    got = json.dumps(payload, indent=2)

    # ---- 1. PARITY: byte-for-byte against the reference implementation's output.
    with open(GOLDEN, encoding="utf-8") as fh:
        want = fh.read()
    check(got == want,
          "port output drifted from the reference payload - diff with:\n"
          "  PYTHONUTF8=1 PYTHONPATH=. python3 aggregate/normalize.py "
          + " ".join(f"--sarif {t}={FIX}/{t}.sarif" for t in TOOLS)
          + " " + " ".join(f"--strip {s}" for s in STRIPS)
          + f" --json /tmp/got.json && diff /tmp/got.json {GOLDEN}")

    by_path = {f["path"]: f for f in payload["findings"]}
    cov = payload["coverage"]

    # ---- 2. The OWN001 umbrella split, which is the whole reason normalization
    #         is not a flat rule->category lookup.
    for path, (cat, name) in {
        "Broker/AmountWindow.xaml.cs": (2, "subscription-leak"),
        "Broker/Poller.cs": (3, "timer-leak"),
        "Broker/Report.cs": (1, "idisposable-leak"),
        "Broker/Pool.cs": (1, "idisposable-leak"),
        "Broker/Io.cs": (1, "idisposable-leak"),          # no tag -> the "*" arm
        "Broker/Escape.cs": (2, "region-escape"),         # OWN014, NOT subscription-leak
        "Broker/View.xaml.cs": (2, "xaml-subscription-leak"),
    }.items():
        f = by_path.get(path)
        check(f is not None and (f["category"], f["category_name"]) == (cat, name),
              f"{path}: expected ({cat},{name}), got "
              f"{None if f is None else (f['category'], f['category_name'])}")
    # the tag is matched case- and space-insensitively
    check(by_path.get("Broker/CaseTag.cs", {}).get("category") == 2,
          "[Resource:  Subscription Token ] must resolve like [resource: subscription token]")

    # ---- 3. Path normalization. Every spelling below is one of the shapes the four
    #         tools really emit; getting any of them wrong misfiles a whole tool's
    #         findings into a module that does not exist.
    for path in ("Broker/Sub/Windows.cs",      # backslashes -> forward slashes
                 "Broker/Scheme.cs",           # file:/// scheme removed, then stripped
                 "Broker/Dotted.cs",           # leading ./ removed
                 "Broker/Longest.cs"):         # LONGEST strip prefix won
        check(path in by_path, f"path normalization lost {path}")
    check(norm_path("/work/target/x.cs", ["/work", "/work/target"]) == "x.cs",
          "the longest strip prefix must win, not the first one listed")

    # ---- 4. Degenerate result shapes still produce a finding rather than a crash or
    #         a silent drop - except the one documented gap.
    check(by_path.get("Broker/NoLine.cs", {}).get("line") == 0,
          "a result with no startLine must read as line 0, not be dropped")
    check(by_path.get("Broker/BadLine.cs", {}).get("line") == 0,
          "a non-integer startLine must read as line 0")
    check(by_path.get("Broker/RuleObj.cs", {}).get("rule") == "OWN001",
          "ruleId must fall back to rule.id")
    check(by_path.get("Broker/NoMessage.cs", {}).get("message") == "",
          "a result with no message text must read as an empty message")
    check(by_path.get("Broker/EmptyRule.cs", {}).get("category") == 0,
          "an empty ruleId must land in uncategorized, not match a glob")
    # KNOWN GAP, pinned so it cannot change unnoticed: a result with no location is
    # dropped and counted nowhere. own-check.sarif carries 20 results; the ledger
    # sees 19. Fixing that is a separate change with a separate payload.
    own_results = json.load(open(os.path.join(FIX, "own-check.sarif"), encoding="utf-8"))
    n_own = sum(len(run.get("results", [])) for run in own_results["runs"])
    n_read = len(parse_sarif(open(os.path.join(FIX, "own-check.sarif"), encoding="utf-8").read(),
                             "own-check", []))
    check((n_own, n_read) == (20, 19),
          f"locationless-result handling changed: {n_read} read of {n_own} results")

    # ---- 5. Suppression is by path OR message, counted and never hidden.
    check(cov["suppressed"] == 2 and cov["suppressed_by"] == {"third-party: DevExpress.": 2},
          f"third-party suppression drifted: {cov['suppressed_by']}")
    check("DevExpress.Xpf/Grid/Helper.cs" not in by_path,
          "a suppressed finding must not appear in the scored findings")
    check("Broker/Cast.cs" not in by_path,
          "suppression must read the message too, not only the path")
    check(cov["total"] - cov["kept"] == cov["suppressed"] + cov["analysis_skipped"],
          "the ledger must account for every finding it drops")

    # ---- 6. Coverage notes are routed out of scoring, not counted as verdicts.
    check(cov["analysis_skipped_by"] == {"OWN050": 1},
          f"OWN050 must be an analysis-skipped note: {cov['analysis_skipped_by']}")
    check("OWN050" not in cov["uncategorized_rules"],
          "a coverage note must not pollute the uncategorized ledger")
    check("Broker/Unknown.cs" not in by_path, "an OWN050 note must not be scored")

    # ---- 7. Unmapped rules surface by name instead of vanishing.
    for rule in ("FOO999", "XAML999", "THREAD_SAFETY_VIOLATION", "NULLPTR_DEREFERENCE",
                 "CS0219", ""):
        check(rule in cov["uncategorized_rules"],
              f"unmapped rule {rule!r} must be surfaced in coverage")

    # ---- 8. Glob precedence: exact beats glob, longer glob beats shorter.
    check(categorize("CA2000", None, tax.rules)[0] == 1, "exact CA2000 must beat the CA2* glob")
    check(categorize("CA2201", None, tax.rules)[0] == 14, "CA2* glob -> general-quality")
    check(categorize("CA1822", None, tax.rules)[0] == 14, "CA1* glob -> general-quality")
    check(categorize("PULSE_RESOURCE_LEAK", None, tax.rules)[0] == 1,
          "*RESOURCE_LEAK glob -> idisposable-leak")
    check(tax.severity_for(1) == "P1" and tax.severity_for(0) == "P3",
          "category severity baseline drifted")

    # ---- 9. Slice-1A boundary, made executable: normalization emits NO identity or
    #         provenance fields. `pattern_id` / `occurrence_id` / `schema_version`
    #         belong to slice 1B, and a field that appears early is a field consumers
    #         start depending on before it means anything.
    emitted = sorted({k for f in payload["findings"] for k in f})
    check(emitted == ["category", "category_name", "line", "message", "path", "resource",
                      "rule", "suppress_reason", "suppressed", "tool"],
          f"the normalized record grew or lost a field: {emitted}")

    # ---- 10. No cross-checkout import in production. The reference reached into a
    #          neighbouring Own.NET worktree with a sys.path.insert; that is exactly
    #          what this port exists to end, so it is asserted rather than trusted.
    #          Parsed, not grepped: the docstrings discuss `oracle_compare` and
    #          `Own.NET` on purpose, and only real import statements are the defect.
    import ast
    for mod in ("normalize.py", "sarif_read.py", "__init__.py"):
        with open(os.path.join(ROOT, "aggregate", mod), encoding="utf-8") as fh:
            tree = ast.parse(fh.read(), filename=mod)
        names: list[str] = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names += [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                names.append(node.module or "")
        for name in names:
            check("oracle_compare" not in name,
                  f"aggregate/{mod}: production imports {name!r} - the port exists to stop "
                  "reading Python out of a neighbouring Own.NET checkout")

    # ---- 11. Taxonomy loader: `_`-prefixed keys are documentation, a non-object
    #          rule spec is an error rather than a category silently reading as 0.
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        p = os.path.join(td, "t.json")
        with open(p, "w", encoding="utf-8") as fh:
            json.dump({"_doc": ["prose"], "rules": {"_note": "prose", "R1": {"category": 7,
                       "name": "x"}}, "category_severity": {"7": "P1"}}, fh)
        t = load_taxonomy(p)
        check(list(t.rules) == ["R1"], f"documentation keys leaked into the rules: {list(t.rules)}")
        check(categorize("R1", None, t.rules) == (7, "x"), "a plain rule spec must still resolve")
        with open(p, "w", encoding="utf-8") as fh:
            json.dump({"rules": {"R1": "not-an-object"}}, fh)
        try:
            load_taxonomy(p)
            fails.append("a malformed rule spec must raise TaxonomyError, not mis-categorize")
        except TaxonomyError:
            pass

    # ---- 12. Reference cross-checks (opt-in: OWNNET_REF=/path/to/Own.NET).
    ref = os.environ.get("OWNNET_REF")
    if not ref:
        skips.append("OWNNET_REF unset: golden re-derivation and YAML transcription re-check "
                     "did not run (they need an Own.NET checkout)")
    else:
        _reference_checks(ref)

    for f in fails:
        print(f"FAIL: {f}")
    for s in skips:
        print(f"SKIP: {s}")
    verdict = ("OK - payload byte-identical to the reference golden"
               if not fails else f"FAIL - {len(fails)} check(s) failed")
    print(f"aggregate/normalize: {verdict} ({len(payload['findings'])} scored of "
          f"{cov['total']} read, {len(TOOLS)} tools), {len(skips)} check(s) skipped")
    return 1 if fails else 0


def _reference_checks(ref: str) -> None:
    """Re-derive the golden from the reference implementation, and re-verify that the
    JSON taxonomy still says what the YAML it was transcribed from says."""
    ref_norm = os.path.join(ref, "audit", "aggregate", "normalize.py")
    ref_yaml = os.path.join(ref, "audit", "static", "taxonomy", "categories.yml")
    if not os.path.exists(ref_norm):
        skips.append(f"OWNNET_REF={ref}: no audit/aggregate/normalize.py there, reference "
                     "checks did not run")
        return

    import subprocess
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        out = os.path.join(td, "ref.json")
        cmd = [sys.executable, ref_norm, "--taxonomy", ref_yaml, "--json", out]
        for tool, path in _inputs():
            cmd += ["--sarif", f"{tool}={path}"]
        for s in STRIPS:
            cmd += ["--strip", s]
        env = {**os.environ, "PYTHONUTF8": "1"}
        proc = subprocess.run(cmd, capture_output=True, text=True, env=env)
        if proc.returncode != 0:
            fails.append(f"reference normalize.py failed (rc={proc.returncode}): "
                         f"{proc.stderr.strip()[:400]}")
            return
        with open(out, encoding="utf-8") as fh:
            regenerated = fh.read()
    with open(GOLDEN, encoding="utf-8") as fh:
        check(regenerated == fh.read(),
              "the committed golden is no longer what the reference implementation "
              "produces - regenerate it and re-read the diff before trusting either side")

    try:
        import yaml
    except ImportError:
        skips.append("PyYAML not importable: taxonomy transcription re-check did not run "
                     "(the audit does not depend on it; this check is developer-only)")
        return
    with open(ref_yaml, encoding="utf-8") as fh:
        y = yaml.safe_load(fh) or {}
    with open(DEFAULT_TAXONOMY, encoding="utf-8") as fh:
        j = json.load(fh)
    for key in ("rules", "category_severity", "suppress", "coverage_notes"):
        a = y.get(key)
        b = j.get(key)
        if key == "category_severity":                 # JSON object keys are strings
            a = {str(k): v for k, v in (a or {}).items()}
        check(a == b, f"taxonomy transcription drifted from the YAML in {key!r}")


if __name__ == "__main__":
    raise SystemExit(main())
