#!/usr/bin/env python3
"""
Normalization: every tool's SARIF -> one categorized findings set.

This is the stage that turns four analyzers' SARIF logs into the
`findings.json` the rest of OwnAudit reads (`report/`, `viz/`, `runtime/`,
`fix/`). It was ported here from the deprecated `Own.NET/audit/aggregate/`
(issue Own.NET#266, slice 1A): OwnAudit is the canonical audit repo, and until
now the pipeline reached across into a neighbouring Own.NET worktree to run the
normalizer - `Run-Audit.ps1` literally invoked `python $Worktree\\audit\\aggregate
\\normalize.py`. Production no longer imports or executes Python from another
checkout.

Three honesty rules, unchanged from the reference implementation:

  * Unmapped rules are **not dropped** - they land in ``uncategorized`` and are
    surfaced in coverage, so the taxonomy grows deliberately.
  * ``OWN001`` is an umbrella leak code; it is split by its ``[resource: ...]``
    tag so subscription/timer leaks (cat. 2/3) are not collapsed into the
    IDisposable bucket (cat. 1).
  * Third-party (DevExpress) findings are baseline-suppressed - dropped from the
    main report but **counted** in coverage, never hidden silently.

WHAT CHANGED IN THE PORT, AND WHY EACH CHANGE IS SAFE
-----------------------------------------------------
The output is byte-identical for the same inputs; `tests/test_normalize.py`
holds a payload generated by the reference implementation and diffs against it.
Only the two seams moved:

  * the SARIF reader is `aggregate/sarif_read.py` (vendored) instead of
    `scripts/oracle_compare.py` reached through a `sys.path.insert` two
    directories up;
  * the taxonomy is JSON instead of YAML, because OwnAudit's Python tooling is
    stdlib-only and CI installs no packages. The mapping is a mechanical
    transcription; the YAML comments live in the file's `_doc` block, and the
    transcription is re-verifiable against the reference file (`OWNNET_REF`).

Nothing about the taxonomy, the suppression rule or the coverage ledger was
"improved" on the way - a port that also changes semantics cannot be checked by
a parity fixture, and the parity fixture is the only reason to believe the port.

Usage:
  normalize.py --sarif own-check=own.sarif --sarif codeql=codeql.sarif \\
               [--taxonomy aggregate/taxonomy/categories.json] \\
               [--strip PREFIX] [--json out.json]
  normalize.py --selftest
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from fnmatch import fnmatchcase
from pathlib import Path
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from aggregate import provenance as prov                                        # noqa: E402
from aggregate.sarif_read import (                                              # noqa: E402,F401
    RawFinding, SarifReadResult, norm_path, parse_sarif, parse_sarif_with_driver,
    read_sarif,
)
from identity import occurrence as occ                                          # noqa: E402
from identity.pattern import pattern_id_of                                      # noqa: E402

RESOURCE_RE = re.compile(r"\[resource:\s*([^\]]+)\]", re.IGNORECASE)

#: The shipped knowledge base. Colocated with its only reader.
DEFAULT_TAXONOMY = Path(__file__).resolve().parent / "taxonomy" / "categories.json"

#: The payload contract. `normalized-findings/v1` is the retroactive name for the
#: unversioned ten-field shape that slice 1A froze; v2 adds identity and
#: provenance ON TOP of it, changing none of those ten fields. A consumer that
#: only knows v1 can still read a v2 record - `aggregate/tests/test_normalize.py`
#: proves that by projecting v2 back down and diffing it against the v1 golden
#: byte for byte.
SCHEMA_VERSION = "normalized-findings/v2"

#: The ten fields slice 1A froze, in order. Kept as data so the projection test
#: and `finding_to_dict` cannot drift apart.
V1_FIELDS = ("tool", "path", "line", "rule", "category", "category_name",
             "resource", "suppressed", "suppress_reason", "message")


@dataclass
class AuditFinding:
    """One analyzer result, categorized. ``fkey`` is the basename (lower-cased) for
    cross-tool matching - robust to the path-prefix differences between tools (one
    reports ``src/Broker/X.cs``, another ``Broker/X.cs``, a third an absolute path)."""

    tool: str
    path: str
    line: int
    rule: str
    message: str
    category: int = 0
    category_name: str = "uncategorized"
    resource: str | None = None
    suppressed: bool = False
    suppress_reason: str = ""
    note: bool = False           # analysis-skipped coverage note (e.g. OWN050), not a verdict
    #: `region.startColumn`, or None when the producer did not report one. Feeds
    #: the physical anchor; deliberately NOT one of the ten emitted v1 fields.
    column: int | None = None
    fkey: str = field(init=False, default="")

    def __post_init__(self) -> None:
        self.fkey = self.path.lower().rsplit("/", 1)[-1]

    @property
    def module(self) -> str:
        """Directory of the finding (the heatmap roll-up unit), or ``(root)``."""
        return self.path.rsplit("/", 1)[0] if "/" in self.path else "(root)"

    @property
    def scored(self) -> bool:
        """A finding counts toward the report only if it is neither third-party
        suppressed nor an analysis-skipped coverage note."""
        return not self.suppressed and not self.note


@dataclass
class Taxonomy:
    rules: dict[str, Any]
    category_severity: dict[int, str]
    suppress_tokens: list[str]
    coverage_note_rules: set[str]

    def severity_for(self, category: int) -> str:
        return self.category_severity.get(category, "P3")


class TaxonomyError(ValueError):
    """The taxonomy file is malformed. Raised instead of mis-categorizing."""


def load_taxonomy(path: str | Path | None = None) -> Taxonomy:
    """Read `categories.json`.

    Keys beginning with `_` are documentation, not data: JSON has no comments, so
    the rationale that lived in the YAML's comments rides along in `_doc` and is
    skipped here. A rule whose spec is not an object is an error rather than a
    later `AttributeError` deep inside matching - a taxonomy typo must fail loudly,
    since the alternative is a whole category quietly reading as `uncategorized`.
    """
    data = json.loads(Path(path or DEFAULT_TAXONOMY).read_text(encoding="utf-8")) or {}
    rules: dict[str, Any] = {}
    for pat, spec in (data.get("rules") or {}).items():
        if pat.startswith("_"):
            continue
        if not isinstance(spec, dict):
            raise TaxonomyError(f"taxonomy rule {pat!r}: expected an object, got {type(spec).__name__}")
        rules[pat] = spec
    sev = {int(k): str(v) for k, v in (data.get("category_severity") or {}).items()
           if not str(k).startswith("_")}
    suppress = list((data.get("suppress") or {}).get("path_or_message_contains") or [])
    notes = {str(r) for r in (data.get("coverage_notes") or [])}
    return Taxonomy(rules=rules, category_severity=sev, suppress_tokens=suppress,
                    coverage_note_rules=notes)


def _resource_tag(message: str) -> str | None:
    m = RESOURCE_RE.search(message or "")
    return m.group(1).strip().lower() if m else None


def _match_rule(rule: str, rules: dict[str, Any]) -> dict[str, Any] | None:
    """Resolve a ruleId to its taxonomy spec. Exact match wins; otherwise the most
    specific glob (longest non-wildcard run) wins."""
    if rule in rules:
        return rules[rule]
    best: tuple[int, dict[str, Any]] | None = None
    for pat, spec in rules.items():
        if any(c in pat for c in "*?[") and fnmatchcase(rule, pat):
            specificity = len(pat.replace("*", "").replace("?", ""))
            if best is None or specificity > best[0]:
                best = (specificity, spec)
    return best[1] if best else None


def categorize(rule: str, resource: str | None,
               rules: dict[str, Any]) -> tuple[int, str]:
    """(category, name) for a ruleId, splitting umbrella codes by resource tag."""
    spec = _match_rule(rule, rules)
    if spec is None:
        return 0, "uncategorized"
    if "by_resource" in spec:
        by = spec["by_resource"]
        chosen = by.get(resource) if resource is not None else None
        if chosen is None:
            chosen = by.get("*", {})
        return int(chosen.get("category", 0)), str(chosen.get("name", "uncategorized"))
    return int(spec.get("category", 0)), str(spec.get("name", "uncategorized"))


def _suppressed(path: str, message: str, tokens: list[str]) -> str:
    """Reason string if this finding is third-party baseline-suppressed, else ''."""
    hay = f"{path}\n{message}".lower()
    for tok in tokens:
        if tok.lower() in hay:
            return f"third-party: {tok}"
    return ""


def normalize_results(raw: list[Any], tax: Taxonomy) -> list[AuditFinding]:
    """Turn RawFindings (tool/path/line/rule/message) into categorized AuditFindings."""
    out: list[AuditFinding] = []
    for f in raw:
        resource = _resource_tag(f.message)
        category, name = categorize(f.rule, resource, tax.rules)
        reason = _suppressed(f.path, f.message, tax.suppress_tokens)
        is_note = f.rule in tax.coverage_note_rules
        out.append(AuditFinding(
            tool=f.tool, path=f.path, line=f.line, rule=f.rule, message=f.message,
            category=category, category_name=name, resource=resource,
            suppressed=bool(reason), suppress_reason=reason, note=is_note,
            column=getattr(f, "column", None)))
    return out


def coverage(findings: list[AuditFinding],
             reads: dict[str, SarifReadResult]) -> dict[str, Any]:
    """The honesty ledger: what was categorized, what was suppressed, which rules
    are analysis-skipped coverage notes, and which rules have no taxonomy entry yet
    (so they are visibly pending, not lost).

    `total` keeps the meaning it has always had - results that could be
    normalized - and does NOT grow to include locationless ones. They are not
    findings; they are results that could not become findings, and the ledger
    states them separately so the two together reconcile against the raw SARIF:

        total + no_physical_location == sum(len(run.results))

    `reads` is required rather than optional. Defaulting it would let a caller
    that never measured the loss emit `no_physical_location: 0`, which reads
    downstream as "measured, none found" - the report-health-you-never-measured
    failure this ledger exists to prevent.
    """
    kept = [f for f in findings if f.scored]
    suppressed = [f for f in findings if f.suppressed]
    notes = [f for f in findings if f.note and not f.suppressed]
    uncategorized = Counter(f.rule for f in kept if f.category == 0)
    lost_by = {tool: dict(r.no_physical_location_by_rule)
               for tool, r in sorted(reads.items()) if r.no_physical_location}
    return {
        "tools": sorted({f.tool for f in findings}),
        "total": len(findings),
        "kept": len(kept),
        "suppressed": len(suppressed),
        "suppressed_by": dict(Counter(f.suppress_reason for f in suppressed)),
        "analysis_skipped": len(notes),
        "analysis_skipped_by": dict(Counter(f.rule for f in notes)),
        "by_category": dict(Counter(f.category for f in kept)),
        "uncategorized_rules": dict(uncategorized),
        #: Results the producers emitted that carry no usable physical location,
        #: so they could not be anchored into findings (#57). Reported, never
        #: silently dropped; see `aggregate/sarif_read.py` for why they are not
        #: admitted with a fabricated `path`/`line`.
        "no_physical_location": sum(r.no_physical_location for r in reads.values()),
        "no_physical_location_by": lost_by,
    }


def normalize(sarif_inputs: list[tuple[str, str]], tax: Taxonomy, strips: list[str],
              ) -> tuple[list[AuditFinding], dict[str, Any], dict[str, str | None]]:
    """Findings, coverage, and each producer's self-declared driver version.

    The version rides along from the same parse rather than costing a second read
    of a 35 MB file - and it is *observed*, not asserted: only CodeQL declares one
    in the recorded corpus.

    Producer names must be unique HERE, not only in `build_payload`. `reads` is
    keyed by producer, so a duplicate name silently keeps both inputs' findings
    while retaining only the last input's locationless count - the two then no
    longer reconcile, which is precisely the accounting #57 exists to make
    trustworthy. Before this function counted anything the collision cost a
    nullable version string and was harmless; it is not harmless now.
    """
    prov.check_unique_producers(sarif_inputs)
    raw: list[Any] = []
    versions: dict[str, str | None] = {}
    reads: dict[str, SarifReadResult] = {}
    for tool, path in sarif_inputs:
        read = read_sarif(Path(path).read_text(encoding="utf-8"), tool, strips)
        raw += read.findings
        versions[tool] = read.driver_version
        reads[tool] = read
    findings = normalize_results(raw, tax)
    return findings, coverage(findings, reads), versions


def finding_to_dict(f: AuditFinding) -> dict[str, Any]:
    """The ten fields slice 1A froze, in their frozen order. Do not extend this -
    identity and provenance are added by `attach_identity`, on top and after."""
    return {
        "tool": f.tool, "path": f.path, "line": f.line, "rule": f.rule,
        "category": f.category, "category_name": f.category_name,
        "resource": f.resource, "suppressed": f.suppressed,
        "suppress_reason": f.suppress_reason, "message": f.message,
    }


# --------------------------------------------------------------------------- #
# Identity (Own.NET#266 slice 1B)                                              #
# --------------------------------------------------------------------------- #

def attach_identity(findings: list[AuditFinding],
                    producers: dict[str, prov.ProducerProvenance]) -> list[dict[str, Any]]:
    """Add `pattern_id`, `occurrence_id`, `physical_anchor` and
    `identity_limitations` to each finding's record.

    `pattern_id` is always computable here - every normalized finding carries
    path, rule and message by construction. `occurrence_id` is not, and the
    honest half of this function is the refusal path.

    AMBIGUITY IS A WHOLE-POPULATION PROPERTY. The anchor census runs over EVERY
    finding read, not only the ones that will be emitted, because whether an
    anchor distinguishes a result is a fact about the producer's run - it does
    not change because the report chose to suppress one of the colliders. Same
    discipline as the runtime witness's root census: presentation limits never
    reach back into classification.
    """
    keys = [
        (f, pattern_id_of(finding_to_dict(f)), occ.anchor(f.path, f.line, f.column))
        for f in findings
    ]
    seen = Counter(
        occ.anchor_key(producers[f.tool].producer_run_id if f.tool in producers else None,
                       f.tool, pid, phys)
        for f, pid, phys in keys
    )

    out: list[dict[str, Any]] = []
    for f, pid, phys in keys:
        p = producers.get(f.tool) or prov.ProducerProvenance(producer_name=f.tool)
        key = occ.anchor_key(p.producer_run_id, f.tool, pid, phys)
        oid, limits = occ.resolve(pid, phys, p.producer_run_id, f.tool,
                                  ambiguous=seen[key] > 1)
        rec = finding_to_dict(f)
        rec["pattern_id"] = pid
        rec["occurrence_id"] = oid
        rec["physical_anchor"] = phys
        rec["identity_limitations"] = limits
        out.append(rec)
    return out


def identity_coverage(records: list[dict[str, Any]]) -> dict[str, Any]:
    """The identity half of the honesty ledger.

    A schema whose flagship field is null for most of the corpus is not a
    failure, but it must not read as a success either - so the counts are
    reported next to the reasons, per producer. `with_occurrence_id` plus
    `without_occurrence_id` always equals the number of emitted records.
    """
    with_id = sum(1 for r in records if r["occurrence_id"])
    by_producer: dict[str, dict[str, int]] = {}
    for r in records:
        b = by_producer.setdefault(r["tool"], {"with_occurrence_id": 0,
                                               "without_occurrence_id": 0})
        b["with_occurrence_id" if r["occurrence_id"] else "without_occurrence_id"] += 1
    return {
        # No `schema_version` here: the payload states it once, at the top level.
        # Two copies are two things to drift apart, and the ledger is not the place
        # to re-declare the contract.
        "with_pattern_id": sum(1 for r in records if r["pattern_id"]),
        "with_occurrence_id": with_id,
        "without_occurrence_id": len(records) - with_id,
        "limitations_by": dict(Counter(
            lim for r in records for lim in r["identity_limitations"]).most_common()),
        "by_producer": by_producer,
    }


def build_payload(sarif_inputs: list[tuple[str, str]], tax: Taxonomy, strips: list[str],
                  manifest_path: str | Path | None = None) -> dict[str, Any]:
    """The `findings.json` document: schema version, the coverage ledger, resolved
    provenance, and the scored findings with their identity.

    Suppressed and analysis-skipped findings are absent from `findings` and present
    in `coverage` - counted, not hidden. Consumers that need the count read the
    ledger; nothing has to infer it from a shortfall.

    `provenance` is a top-level map keyed by producer name rather than a copy
    inside each record: the six fields are identical for every finding of a
    producer, and duplicating them across the 72 559 records of the STS corpus
    would multiply the payload for no information. Each record's existing `tool`
    IS the join key.
    """
    # Before a byte of SARIF is read: two inputs under one producer name cannot be
    # represented, and a malformed manifest is worth finding out about now rather
    # than after parsing 100 MB of input. The manifest is read ONCE here and handed
    # to both consumers below. `normalize` and `prov.resolve` each re-check
    # uniqueness for callers that reach them directly, which costs a loop over four
    # items and keeps the invariant true no matter who calls - this comment used to
    # claim that while `normalize`, which reaches neither, was the one path that
    # could count a duplicate instead of refusing it.
    prov.check_unique_producers(sarif_inputs)
    entries = prov.load_manifest(manifest_path) if manifest_path else {}
    findings, cov, versions = normalize(sarif_inputs, tax, strips)
    producers = prov.resolve(sarif_inputs, manifest_path, versions, entries)
    records = [r for r in attach_identity(findings, producers)
               if not r["suppressed"] and r["rule"] not in tax.coverage_note_rules]
    cov["identity"] = identity_coverage(records)
    unused = prov.unused_entries(sarif_inputs, manifest_path, entries)
    if unused:
        cov["provenance_unused_entries"] = unused
    return {
        "schema_version": SCHEMA_VERSION,
        "coverage": cov,
        "provenance": {name: p.to_dict() for name, p in sorted(producers.items())},
        "findings": records,
    }


def project_v1(payload: dict[str, Any]) -> dict[str, Any]:
    """A v2 payload seen through v1 eyes: the ten frozen fields and the ledger the
    port was pinned against.

    This exists so the 1A parity golden - which was generated by the REFERENCE
    implementation, not by this code - keeps meaning something after the schema
    grew. If this projection ever stops matching those bytes, 1B changed
    something it promised only to add to.

    Every later slice that ADDS a coverage key excludes it here, and the golden
    stays exactly what the reference wrote. Editing the golden instead would work
    once and cost the file its meaning: a diff against a fresh reference run is
    supposed to say "the port drifted", and a hand-edited golden makes it say
    "the port drifted, or someone touched this on purpose, and you cannot tell
    which". `no_physical_location*` are #57's keys; the reference has nothing to
    say about them by construction, being the implementation that dropped
    locationless results without counting them.
    """
    cov = {k: v for k, v in payload["coverage"].items()
           if k not in ("identity", "provenance_unused_entries",
                        "no_physical_location", "no_physical_location_by")}
    return {"coverage": cov,
            "findings": [{k: r[k] for k in V1_FIELDS} for r in payload["findings"]]}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Normalize SARIF into categorized findings.")
    ap.add_argument("--sarif", action="append", default=[], metavar="TOOL=PATH",
                    help="a tool's SARIF as tool=path (repeatable)")
    ap.add_argument("--taxonomy", default=str(DEFAULT_TAXONOMY),
                    help="categories.json (default: the shipped taxonomy)")
    ap.add_argument("--strip", action="append", default=[], metavar="PREFIX",
                    help="path prefix to strip from finding paths (repeatable)")
    ap.add_argument("--provenance", default=None, metavar="MANIFEST",
                    help="producer-provenance/v1 manifest naming each producer's run "
                         "(without it every occurrence_id is null, and says why)")
    ap.add_argument("--json", dest="json_out", default="",
                    help="write normalized findings + coverage as JSON")
    ap.add_argument("--selftest", action="store_true",
                    help="run built-in checks and exit")
    args = ap.parse_args(argv)

    if args.selftest:
        return _selftest()

    inputs: list[tuple[str, str]] = []
    for spec in args.sarif:
        tool, _, path = spec.partition("=")
        if not path:
            ap.error(f"--sarif expects tool=path, got {spec!r}")
        inputs.append((tool, path))

    tax = load_taxonomy(args.taxonomy)
    try:
        payload = build_payload(inputs, tax, args.strip, args.provenance)
    except prov.ProvenanceError as e:
        # Rejected, not degraded: falling back to "run unknown" on a mismatched
        # manifest would turn a wrong claim into a slightly emptier report, and
        # nobody investigates a slightly emptier report.
        print(f"normalize: {e}", file=sys.stderr)
        return 2
    if args.json_out:
        Path(args.json_out).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(json.dumps(payload["coverage"], indent=2))
    return 0


# --------------------------------------------------------------------------- #
# Selftest - embedded fixtures.                                                #
# --------------------------------------------------------------------------- #

def _own_sarif() -> str:
    """own-check-style SARIF exercising the OWN001 [resource:] split + OWN014."""
    def res(rule: str, msg: str, uri: str, line: int) -> dict[str, Any]:
        return {"ruleId": rule, "level": "warning", "message": {"text": msg},
                "locations": [{"physicalLocation": {
                    "artifactLocation": {"uri": uri}, "region": {"startLine": line}}}]}
    return json.dumps({"version": "2.1.0", "runs": [{"tool": {"driver": {"name": "Own.NET"}},
        "results": [
            res("OWN001", "event subscribed but never unsubscribed [resource: subscription token]",
                "src/Vm/CustomerViewModel.cs", 12),
            res("OWN001", "timer never stopped [resource: timer]", "src/Vm/TimerViewModel.cs", 30),
            res("OWN001", "field never disposed [resource: disposable field]",
                "src/Vm/ReportViewModel.cs", 7),
            res("OWN001", "local IDisposable never disposed", "src/Util/Io.cs", 9),
            res("OWN014", "region escape: view-model promoted to App lifetime",
                "src/Vm/StaticEventEscapeViewModel.cs", 50),
            res("OWN050", "cannot verify 'X.Y' - unresolved [resource: unresolved reference]",
                "src/Util/Unknown.cs", 3),
        ]}]})


def _codeql_sarif() -> str:
    def res(rule: str, uri: str, line: int) -> dict[str, Any]:
        return {"ruleId": rule, "message": {"text": "not disposed"},
                "locations": [{"physicalLocation": {
                    "artifactLocation": {"uri": uri}, "region": {"startLine": line}}}]}
    return json.dumps({"runs": [{"results": [
        res("cs/local-not-disposed", "src/Util/Io.cs", 9),          # agrees with own local leak
        res("cs/empty-block", "DevExpress.Xpf/Grid/Helper.cs", 4),  # third-party -> suppressed
        res("FOO999", "src/Util/Misc.cs", 3),                       # unmapped -> uncategorized
    ]}]})


def _selftest() -> int:
    checks: list[str] = []

    def check(ok: bool, msg: str) -> None:  # total derives from the call count
        checks.append("" if ok else msg)

    # The shipped taxonomy must parse and carry the split that the OWN001 fix needs.
    tax = load_taxonomy()
    check("by_resource" in tax.rules.get("OWN001", {}),
          "shipped categories.json lost the OWN001 by_resource split")
    check(tax.rules.get("OWN014", {}).get("name") == "region-escape",
          "shipped categories.json: OWN014 must be region-escape, not subscription-leak")

    own_read = read_sarif(_own_sarif(), "own-check", [])
    own = normalize_results(own_read.findings, tax)
    by_file = {f.fkey: f for f in own}

    # OWN001 umbrella split by [resource: ...] tag.
    cases = {
        "customerviewmodel.cs": (2, "subscription-leak"),
        "timerviewmodel.cs": (3, "timer-leak"),
        "reportviewmodel.cs": (1, "idisposable-leak"),
        "io.cs": (1, "idisposable-leak"),                # no resource tag -> "*" fallback
        "staticeventescapeviewmodel.cs": (2, "region-escape"),
    }
    for fkey, (cat, name) in cases.items():
        got = by_file.get(fkey)
        check(got is not None and (got.category, got.category_name) == (cat, name),
              f"{fkey}: expected ({cat},{name}), got "
              f"{None if got is None else (got.category, got.category_name)}")

    # OWN050 is an analysis-skipped coverage note, not a verdict: routed out of
    # scoring, never a phantom uncategorized P3 candidate.
    own050 = by_file.get("unknown.cs")
    check(own050 is not None and own050.note and not own050.scored,
          "OWN050 must be a coverage note (note=True, scored=False)")

    # Glob mapping + uncategorized + DevExpress suppression on the CodeQL run.
    cq_read = read_sarif(_codeql_sarif(), "codeql", [])
    cq = normalize_results(cq_read.findings, tax)
    cq_by = {f.fkey: f for f in cq}
    check(cq_by["io.cs"].category == 1, "cs/local-not-disposed should map to category 1")
    check(cq_by["helper.cs"].suppressed, "DevExpress finding must be baseline-suppressed")
    check(cq_by["misc.cs"].category == 0, "unmapped FOO999 must be uncategorized (category 0)")

    cov = coverage(own + cq, {"own-check": own_read, "codeql": cq_read})
    check(cov["suppressed"] == 1, f"coverage suppressed count wrong: {cov['suppressed']}")
    # These inline samples are all anchored, so the ledger must say so with a
    # measured zero - which it may, having actually read them.
    check(cov["no_physical_location"] == 0 and cov["no_physical_location_by"] == {},
          f"inline samples carry no locationless results: {cov['no_physical_location']}")
    check(cov["analysis_skipped"] == 1 and cov["analysis_skipped_by"].get("OWN050") == 1,
          "OWN050 must be counted as analysis-skipped in coverage")
    check("OWN050" not in cov["uncategorized_rules"],
          "OWN050 (a coverage note) must not pollute uncategorized rules")
    check(cov["uncategorized_rules"].get("FOO999") == 1,
          "uncategorized rule FOO999 must be surfaced in coverage exactly once")
    # a suppressed finding must not leak into the kept category tally
    check(cov["by_category"].get(0, 0) == 1,
          f"suppressed finding leaked into kept categories: {cov['by_category']}")

    # severity baseline comes from the category, not the tool level
    check(tax.severity_for(1) == "P1" and tax.severity_for(0) == "P3",
          "category severity baseline wrong")

    # glob specificity: CA2000 (exact, cat 1) must beat CA2* (glob, cat 14)
    check(categorize("CA2000", None, tax.rules)[0] == 1,
          "exact CA2000 should win over CA2* glob")
    check(categorize("CA1822", None, tax.rules)[0] == 14,
          "CA1* glob should map to general-quality (14)")

    fails = [c for c in checks if c]
    for f in fails:
        print(f"NORMALIZE SELFTEST FAIL: {f}")
    print(f"normalize selftest: {len(checks) - len(fails)}/{len(checks)} checks passed")
    return 1 if fails else 0


if __name__ == "__main__":
    raise SystemExit(main())
